spring.application.name=backend-chat
server.port=${PORT:8080}
# Configuración de Supabase
spring.datasource.url=jdbc:postgresql://db.dppuznmtnybefucyztaj.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=9QJezUH2Ys5Fk3FX
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate - Crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
