# Configuración del puerto para Render
server.port=${PORT:8080}

spring.application.name=backend-chat

# Configuración de Supabase (SQL)
spring.datasource.url=jdbc:postgresql://db.dppuznmtnybefucyztaj.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=9QJezUH2Ys5Fk3FX
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
